### ISSUE TITLE
Failed to determine the most recently installed Android SDK version

### ISSUE THREAD

**Issue by unace** [googlesamples/unity-jar-resolver#320]
Please fill in the following fields:
Unity editor version: 2019.3.0f6
Play Services Resolver version: 
1.2.133
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): 
I don't know exactly... maybe Android Resolver?
Plugins SDK in use (Firebase, Admob, Facebook, etc.): 
Firebase 6.9.0
Platform you are using the Unity editor on (Mac, Windows, or Linux): 
Mac
Platform you are targeting (iOS, Android, and/or desktop): 
Android
Scripting Runtime (Mono, and/or IL2CPP):
IL2CPP

Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

Hi,
I got this error whenever running Unity.

I haven't installed Oracle JDK manually, but I installed Unity with Open JDK (path : /Applications/Unity/Hub/Editor/2019.3.0f6/PlaybackEngines/AndroidPlayer/OpenJDK).
Do I have to install Oracle JDK?

Please let me know if you need more information.

First log
```
Failed to get Java version when running /usr/bin/java
It is not be possible to verify your Java installation is new enough to compile with the latest Android SDK

Failed to run '/usr/bin/java -version'
stdout:

stderr:
No Java runtime present, requesting install.

exit code: 1

UnityEngine.Debug:LogWarning(Object)
Google.Logger:Log(String, LogLevel) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/Logger.cs:120)
GooglePlayServices.PlayServicesResolver:Log(String, LogLevel) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:967)
GooglePlayServices.JavaUtilities:LogJdkVersionFailedWarning(String, String) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/JavaUtilities.cs:163)
GooglePlayServices.JavaUtilities:CheckJdkForApiLevel() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/JavaUtilities.cs:189)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1634)
GooglePlayServices.<ScheduleResolve>c__AnonStorey5:<>m__0() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1604)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1461)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1134)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)
```
Second log 
```
Unable to list target platforms. Please make sure the android sdk path is correct. 
No Java runtime present, requesting install.

UnityEditor.Android.CommandInvokationFailure: Unable to list target platforms. Please make sure the android sdk path is correct. 
/Applications/Unity/Hub/Editor/2019.3.0f6/PlaybackEngines/AndroidPlayer/SDK/tools/bin/avdmanager list target -c

stderr[
No Java runtime present, requesting install.
]
stdout[

]
exit code: 1
  at UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00033] in <501fdf9059b849939e0297808b46ab08>:0 
  at UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) [0x00017] in <501fdf9059b849939e0297808b46ab08>:0 
  at UnityEditor.Android.AndroidSDKTools.RunAndroidSdkTool (System.String toolName, System.String arguments, System.Boolean updateCommand, System.String errorMsg, System.String toolsDir) [0x0007a] in <501fdf9059b849939e0297808b46ab08>:0 
  at UnityEditor.Android.AndroidSDKTools.RunAndroidSdkTool (System.String toolName, System.String arguments, System.Boolean updateCommand, System.String errorMsg) [0x00001] in <501fdf9059b849939e0297808b46ab08>:0 
  at UnityEditor.Android.AndroidSDKTools.ListTargetPlatforms () [0x00009] in <501fdf9059b849939e0297808b46ab08>:0 
System.Reflection.MethodBase:Invoke(Object, Object[])
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:263)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:121)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2314)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1635)
GooglePlayServices.<ScheduleResolve>c__AnonStorey5:<>m__0() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1604)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1461)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1134)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)
```
Third log
```
Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogWarning(Object)
GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:239)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:314)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/UnityCompat.cs:121)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2314)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1635)
GooglePlayServices.<ScheduleResolve>c__AnonStorey5:<>m__0() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1604)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1461)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1134)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__8() (at Z:/tmp/tmp.xf9HY6bEAq/third_party/unity/unity_jar_resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113)
Google.RunOnMainThread:ExecutePollingJobs() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__1() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at Z:/tmp/tmp.D3TY3fsrzI/third_party/unity/unity_jar_resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)

```

Please answer the following, if applicable:
100%

repro steps
1. prepare Mac that doesn't have /usr/bin/java.
1. install Unity 2019.3.0f6
1. download Firebase Unity SDK 6.9.0
1. create a Unity 3D project
1. import Firebase package
1. switch target platform to Android
1. reopen the project

**Comment by paulinon** [comment]
Thanks for reporting this issue, @unace. I'll see if I can try to reproduce this issue on my end. In the meantime, could you try making use of the updated versions of your Play Services Resolver and Firebase SDK to see if the issue still persists?

**Comment by unace** [comment]
hi @paulinon , I am still facing the same issue with the updated version (Play Services Resolver version:
1.2.135, Firebase version: 6.10.0). I forgot to mention the "switching to Android platform" step, just added to repro steps.

**Comment by paulinon** [comment]
Hi @unace, your issue may have something to do with a newer Java release returning a different status code or version string. Could you try running `java -version; echo $?` and share the results so we can see what's going on?

**Comment by unace** [comment]
It returns "No Java runtime present, requesting install."
That's why I asked "I haven't installed Oracle JDK manually, installed Unity with Open JDK (path : /Applications/Unity/Hub/Editor/2019.3.0f6/PlaybackEngines/AndroidPlayer/OpenJDK).
Do I have to install Oracle JDK?"

**Comment by paulinon** [comment]
It appears that the configuration of the Java tools location is broken. Try installing Oracle JDK and see if it works.

**Comment by unace** [comment]
It sounds Oracle JDK is required to use unity jar resolver. If so, could you add it to requirements documentation (https://github.com/googlesamples/unity-jar-resolver#requirements)? It would be helpful.

**Comment by TheOneVries** [comment]
Came here due to the same error, using Unity 2019.3.1f1.
_I do have Oracle JDK installed though_

> Failed to determine the most recently installed Android SDK version. Please report this as a bug with the version of Unity you are using at: https://github.com/googlesamples/unity-jar-resolver/issues Resorting to reading a fallback value from the editor preferences GooglePlayServices.PlatformVersionFallback: 25
UnityEngine.Debug:LogWarning(Object)
GooglePlayServices.UnityCompat:WarnOnAndroidSdkFallbackVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:239)
GooglePlayServices.UnityCompat:FindNewestInstalledAndroidSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:314)
GooglePlayServices.UnityCompat:GetAndroidTargetSDKVersion() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/UnityCompat.cs:121)
GooglePlayServices.PlayServicesResolver:CanEnableJetifierOrPromptUser(String) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:2314)
GooglePlayServices.PlayServicesResolver:ResolveUnsafe(Action`1, Boolean, Boolean, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1635)
GooglePlayServices.<ScheduleResolve>c__AnonStorey1E:<>m__3F() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1604)
GooglePlayServices.PlayServicesResolver:ExecuteNextResolveJob() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1461)
GooglePlayServices.PlayServicesResolver:ScheduleResolve(Boolean, Boolean, Action`1, Boolean) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1617)
GooglePlayServices.PlayServicesResolver:AutoResolve(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1134)
GooglePlayServices.PlayServicesResolver:<ScheduleAutoResolve>m__47() (at /Users/smiles/dev/src/unity-jar-resolver/source/PlayServicesResolver/src/PlayServicesResolver.cs:1113)
Google.RunOnMainThread:ExecutePollingJobs() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:300)
Google.RunOnMainThread:<ExecuteAll>m__A() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:414)
Google.RunOnMainThread:RunAction(Action) (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:234)
Google.RunOnMainThread:ExecuteAll() (at /Users/smiles/dev/src/unity-jar-resolver/source/VersionHandlerImpl/src/RunOnMainThread.cs:406)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by unace** [comment]
I think I found the reason. The OpenJDK path seems to be changed from certain Unity version (2019.3.0 and 2019.3.1 verified on mac). I made a pull request to fix this. https://github.com/googlesamples/unity-jar-resolver/pull/325

**Comment by sp-jordi-vilalta** [comment]
This may be related to #323 and I think it may also be solved by using [AndroidExternalToolsSettings](https://docs.unity3d.com/ScriptReference/Android.AndroidExternalToolsSettings.html) when available.

**Comment by unace** [comment]
@sp-jordi-vilalta thanks for the information.  The AndroidExternalToolsSettings API seems to be added to 2019.3.0. but it doesn't work with 2019.3.2f1 on my mac.
```
#if UNITY_2019_3_OR_NEWER && UNITY_ANDROID
        Debug.Log(UnityEditor.Android.AndroidExternalToolsSettings.jdkRootPath);
#endif
```
this code leads an error.
`Assets/Test.cs(10,19): error CS0234: The type or namespace name 'AndroidExternalToolsSettings' does not exist in the namespace 'UnityEditor.Android' (are you missing an assembly reference?)`
This looks like a Unity error so I reported it to Unity.

**Comment by paulinon** [comment]
Hi everyone. Version 1.2.136 has been released which fixed OpenJDK path discovery in Unity 2019.3.1. Could you try using these versions on your end and see if the issue has been resolved? Thanks.

**Comment by unace** [comment]
I made a new MR(https://github.com/googlesamples/unity-jar-resolver/pull/329) to fix this. Thanks @sp-jordi-vilalta
