### ISSUE TITLE
Android resolver issues with Unity 2019.3 and Multidex

### ISSUE THREAD

**Issue by mvaivre** [googlesamples/unity-jar-resolver#296]
### Context:
Unity editor version: **2019.3b10**
Play Services Resolver version: **1.2.131**
Features in Play Services Resolver in use (Android Resolver, iOS Resolver, VersionHandler, etc.): **Android Resolver**
Plugins SDK in use (Firebase, Admob, Facebook, etc.): **Appodeal, Google Play Games**
Platform you are using the Unity editor on (Mac, Windows, or Linux): **Mac**
Platform you are targeting (iOS, Android, and/or desktop): **Android**
Scripting Runtime (Mono, and/or IL2CPP): **IL2CPP**

### Issues:
I've hit many issues when building with Gradle while trying to add Appodeal, which requires Multidex. Let me try to summarise the roadblocks I encountered:

1) When trying to activate Multidex `com.android.support:multidex:1.0.3` i'm seing the error **"More than one file was found with OS independent path 'androidsupportmultidexversion.txt'"** which seems to indicate that two different version of Multidex are conflicting. By using `gradle androidDependencies`, I was able to see that an AndroidX version of Multidex was already included in the build, but I've no idea where it comes from :/

2) By pinning the multidex version to the AndroidX version, I got rid of the issue shown above... but then multidex is not enabled (ie. the >65k methods error is back).

3) Finally, when adding Google Play Games, I'm seeing the error **"Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy"** which seems to indicate another conflict between Appodeal and Play Games dependencies. Shouldn't dependency merges be normally handled by the resolver?

I've tried all kind of settings in the resolver (deactivate Gradle file patching, Jetifier is on...), it never worked. 

Could those issues be caused by the new "Unity as a library" implementation (as of 2019.3), that introduces a new project structure? => https://forum.unity.com/threads/using-unity-as-a-library-in-native-ios-android-apps.685195/

Does anyone succeed in having the resolver + multidex working with Unity 2019.3? 

Thanks so much in advance for your help!

**Comment by mvaivre** [comment]
So, to add some info about my 3rd point, this is actually linked to [this issue](https://github.com/googlesamples/unity-jar-resolver/issues/241) that is still not actually resolved. If I build with "mainTemplate patching" on, I get the error shown above. If I don't patch the file, then Jetifier is off and my app is crashing when starting. Before Unity 2019.3, I believe that you could use the workaround explained here: https://github.com/googlesamples/unity-jar-resolver/issues/241#issuecomment-514995546
But now we have 2 Gradle files: one for the launcher, and one for the library. The workaround shown above doesn't seem to work anymore.

So the only solution I saw for now was to stop using the resolver with Appodeal (ie. proceed to a manual install of Appodeal deps), and use a min Android SDK of 21 to avoid having to export the project and patch the gradle files manually....

But this brought another issue:
"java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider"
"Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider"

This was actually caused by the resolver deleting the dependencies which were added manually.
Anyway, I think that's enough frustrating roadblocks for today, let's see if tomorrow will be any better.

**Comment by mvaivre** [comment]
Last update, if anyone is stuck in the same situation: I managed to build the app with some help from the Appodeal team. They supplied me with a new Beta SDK (now available on their website), which works fine. Just make sure to:

- Deactivate the patching of mainTemplate.gradle
- Add android:name="androidx.multidex.MultiDexApplication" tools:replace="android:name" in your manifest application tag.

**Comment by hanilozmen** [comment]
The same problem is valid for me.
Unity Editor version **2019.3.03f** 
 Jar resolver version **1.2.135** 

mvaive's solution did not work me. I turned back to Unity Editor 2019.2.17f and the problem disappeared. So, using Unity Editor v2019.2.x  is the best choice for now.

**Comment by Thaina** [comment]
I too have this problem with both 2019.3 and 2020

**Comment by Thaina** [comment]
I can confirm that creating blank project, add facebook sdk and google play service causing error

```
  java.lang.RuntimeException: Duplicate class android.support.v4.app.INotificationSideChannel found in modules classes.jar (androidx.core:core:1.0.0) and classes.jar (com.android.support:support-compat:27.0.2)
```

And some more duplicated class in `support-compat`

**Comment by eladleb** [comment]
Hey @stewartmiles I was wondering if you guys have any input on this issue?

**Comment by stewartmiles** [comment]
This sounds like a duplicate of https://github.com/googlesamples/unity-jar-resolver/issues/243 where multiple plugins include the same dependency and the mainTemplate.gradle patcher just includes all of them.  We haven't had time to add support for this yet so you'll need to dedupe the mainTemplate.gradle file manually after running the resolver.

**Comment by Thaina** [comment]
@stewartmiles Is it any difference between build unity directly as in 2018 and build unity as library in 2019?

I think it's normal that resolver bring multiple library in there, it could build normally for such times, only break in 2019 when it force us to build as library

**Comment by stewartmiles** [comment]
@Thaina the only difference is when using the `mainTemplate.gradle` patching mode (no deduping) vs. the old dumping the Android libraries into `Plugins/Android` mode.  The old mode runs Gradle and dedupes libraries which is really slow but it actually dedupes.

**Comment by Thaina** [comment]
@stewartmiles Well, I means, I have been using the `mainTemplate.gradle` for year, is it patching mode? I don't know because resolving it still make it redownload `aar` in my project (firebase and google play service in `m2repository`)

This process start having problem when I migrate to 2019, the difference of unity side is it start forcing us to build project `as a library` or something like that. Which make me wonder what the difference that it affect the resolver system

**Comment by sp-ivan-hernandez** [comment]
Hello,

we also had the "java.lang.RuntimeException: Duplicate class" errors in 2019.3 but not in 2019.2

our fix was to add in the **build.gradle** of the **launcher** the

```
([rootProject] + (rootProject.subprojects as List)).each {
    ext {
        it.setProperty("android.useAndroidX", true)
        it.setProperty("android.enableJetifier", true)
    }
}
```

at the beginning  of the file, since having this only in the **unityLibrary** **build.gradle** was not enough.

**Comment by sp-jordi-vilalta** [comment]
As @sp-ivan-hernandez mentioned, in Unity 2019.3, the patched `mainTemplate.gradle` file is located in the `unityLibrary` module. In addition to that there's also a root project and a `launcher` module:
```
root
 +- launcher
 `- unityLibrary
```
I think the problem is that code patched in the `mainTemplate.gradle` file only runs when configuring the `unityLibrary` module, which is not the root project anymore. The code that injects configuration to other projects is not ran when expected. In practice that means this is only applied to `unityLibrary` and its submodules, but not to the root project nor the `launcher` module.
Moving this snippet to the top-level `build.gradle` file fixes the issue. The alternative solution is manually adding the settings [as suggested](https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio) to the top-level `gradle.properties` file.

**Comment by Thaina** [comment]
Thank you, will try it when possible
